import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <div className="flex min-h-screen w-screen items-center justify-center">
          <Main />
        </div>
        <NextScript />
      </body>
    </Html>
  );
}
